# Generated by Django 3.1.2 on 2020-10-23 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=255)),
                ('data_nascimento', models.DateField()),
                ('endereco', models.CharField(max_length=255)),
                ('whatsapp', models.CharField(max_length=11)),
                ('email', models.CharField(max_length=50)),
                ('problema', models.TextField(blank=True)),
                ('dia_semana', models.DateField()),
                ('horario', models.CharField(max_length=255)),
            ],
        ),
    ]
