# Generated by Django 3.1.2 on 2020-10-22 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_auto_20201022_0106'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='problema',
            field=models.TextField(blank=True),
        ),
    ]
